SAMPLE_EMAILS = [
    {
        "id": "demo-google-1",
        "company": "Google",
        "from": "Google Recruiting <no-reply@google.com>",
        "subject": "Software Engineer, AI Products application received",
        "date": "Mon, 15 Jun 2026 09:30:00 -0400",
        "category": "Application Submitted",
        "snippet": "Thank you for applying to Software Engineer, AI Products. We received your application.",
        "body_preview": "Thank you for applying to Software Engineer, AI Products. We received your application and our hiring team will review your profile.",
        "status": "Applied",
        "next_action": "Wait 5-7 business days, then follow up with recruiter or referral contact.",
        "summary": "Application submitted for a software engineering role related to AI products.",
        "days_since_last_email": 3,
    },
    {
        "id": "demo-amazon-1",
        "company": "Amazon",
        "from": "Amazon Recruiting <recruiting@amazon.jobs>",
        "subject": "Online assessment invitation for Data Engineer",
        "date": "Tue, 16 Jun 2026 13:15:00 -0400",
        "category": "Online Assessment",
        "snippet": "Please complete your online assessment for the Data Engineer role within 5 days.",
        "body_preview": "Please complete your online assessment for the Data Engineer role within 5 days. The assessment includes SQL, Python, and data modeling questions.",
        "status": "Online Assessment",
        "next_action": "Complete assessment and practice SQL/Python before starting.",
        "summary": "Amazon sent an online assessment for a Data Engineer role.",
        "days_since_last_email": 2,
    },
    {
        "id": "demo-tesla-1",
        "company": "Tesla",
        "from": "Tesla Talent Acquisition <talent@tesla.com>",
        "subject": "Interview availability - AI Data Analyst",
        "date": "Wed, 17 Jun 2026 10:45:00 -0400",
        "category": "Interview",
        "snippet": "We would like to schedule a technical interview for the AI Data Analyst position.",
        "body_preview": "We would like to schedule a technical interview for the AI Data Analyst position. Please share your availability for next week.",
        "status": "Interview",
        "next_action": "Reply with availability and prepare Python, SQL, analytics, and ML project stories.",
        "summary": "Tesla requested interview availability for an AI/data role.",
        "days_since_last_email": 1,
    },
    {
        "id": "demo-meta-1",
        "company": "Meta",
        "from": "Meta Careers <careers@meta.com>",
        "subject": "Update on your Machine Learning Engineer application",
        "date": "Thu, 18 Jun 2026 08:00:00 -0400",
        "category": "Rejection",
        "snippet": "After careful consideration, we will not be moving forward with your application at this time.",
        "body_preview": "After careful consideration, we will not be moving forward with your application at this time. We encourage you to apply again in the future.",
        "status": "Rejected",
        "next_action": "No action needed. Track rejection and apply to similar roles.",
        "summary": "Meta declined the current application.",
        "days_since_last_email": 0,
    },
    {
        "id": "demo-apple-1",
        "company": "Apple",
        "from": "Apple Recruiter <recruiter@apple.com>",
        "subject": "Following up on your AI/ML background",
        "date": "Wed, 17 Jun 2026 16:20:00 -0400",
        "category": "Recruiter Message",
        "snippet": "Your AI/ML and software background looks relevant. Could you share your latest resume?",
        "body_preview": "Your AI/ML and software background looks relevant. Could you share your latest resume and availability for an introductory conversation?",
        "status": "Recruiter Replied",
        "next_action": "Send updated resume and 2-3 availability slots.",
        "summary": "Apple recruiter requested resume and availability.",
        "days_since_last_email": 1,
    },
    {
        "id": "demo-microsoft-1",
        "company": "Microsoft",
        "from": "Microsoft Talent <talent@microsoft.com>",
        "subject": "Offer letter for Data & AI Engineer",
        "date": "Fri, 19 Jun 2026 12:00:00 -0400",
        "category": "Offer",
        "snippet": "We are pleased to offer you the Data & AI Engineer position.",
        "body_preview": "We are pleased to offer you the Data & AI Engineer position. Please review the offer details and respond by the deadline.",
        "status": "Offer",
        "next_action": "Review offer details and respond before the deadline.",
        "summary": "Microsoft sent an offer for a Data & AI Engineer position.",
        "days_since_last_email": 0,
    },
    {
        "id": "demo-quora-ignored",
        "company": "Quora Digest",
        "from": "Quora Digest <digest-noreply@quora.com>",
        "subject": "What is it like to be an MBA from IIM?",
        "date": "Thu, 18 Jun 2026 03:10:22 +0000",
        "category": "Not Job Related",
        "snippet": "This is a digest/newsletter and should not affect job analytics.",
        "body_preview": "This is not job related content.",
        "status": "Not Job Related",
        "next_action": "No action needed",
        "summary": "Ignored newsletter/non-job email.",
        "days_since_last_email": 0,
    },
]
